M48
; DRILL file {KiCad (6.0.10)} date Wed Feb 15 12:42:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T12:42:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X3.3224Y-1.5862
X3.3224Y-1.8138
T2
X3.5469Y-1.563
X3.6651Y-1.563
T0
M30
